[build]
pre-build = [ # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update",
    "apt install mold wget libwayland-dev:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH librust-libudev-sys-dev:$CROSS_DEB_ARCH",
    "bash -c \"$(wget -O - https://apt.llvm.org/llvm.sh)\"",
    "for file in /usr/lib/llvm-18/bin/*; do sudo ln -sf \"$file\" \"/bin/$(basename \"$file\")\"; done",
]
