[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update",
    "apt install -y wget mold lsb-release wget software-properties-common gnupg librust-wayland-client-dev librust-wayland-sys-dev build-essential pkg-config g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libxkbcommon-dev libwayland-dev librust-alsa-sys-dev",
    "wget https://apt.llvm.org/llvm.sh",
    "chmod +x llvm.sh",
    "./llvm.sh 18",
]

[target.aarch64-unknown-linux-musl]
image = "ubuntu:noble"

[target.x86_64-unknown-linux-musl]
image = "ubuntu:jammy"

[target.aarch64-unknown-linux-gnu]
image = "ubuntu:noble@sha256:820a8779863b9b666fd1585cd79b2d8e213b1193e4264c56239d90e9df3b0542"

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:jammy"
