[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update",
    "apt install -y wget mold lsb-release wget software-properties-common gnupg build-essential pkg-config libwayland-dev librust-alsa-sys-dev",
    "wget https://apt.llvm.org/llvm.sh",
    "chmod +x llvm.sh",
    "./llvm.sh 18",
]

[target.aarch64-unknown-linux-musl]
image = "ubuntu:jammy"

[target.x86_64-unknown-linux-musl]
image = "ubuntu:jammy"

[target.aarch64-unknown-linux-gnu]
image = "ubuntu:jammy"

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:jammy"
